# Generated by Django 4.2.6 on 2023-12-09 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("card_number", models.AutoField(primary_key=True, serialize=False)),
                ("expire_date", models.DateField()),
                ("CVV", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("fullname", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("category", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(default="", max_length=250, null=True),
                ),
                ("quantity", models.IntegerField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="uploads/flower/")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_number", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Placed", "Placed"),
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Placed",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppFolder.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_number", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "card_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppFolder.creditcard",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppFolder.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppFolder.flower",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppFolder.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creditcard",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppFolder.customer",
                unique=True,
            ),
        ),
    ]
