# Generated by Django 4.2.6 on 2023-12-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFolder", "0002_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
