# Generated by Django 4.2.6 on 2023-12-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppFolder", "0004_alter_customer_groups_alter_customer_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="order",),
    ]
