# Generated by Django 4.2.6 on 2023-12-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFolder", "0005_remove_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="amount",),
        migrations.RemoveField(model_name="orderitem", name="amount",),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(to="AppFolder.orderitem"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Placed", "Placed"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
