# Generated by Django 4.2.6 on 2023-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFolder", "0006_remove_order_amount_remove_orderitem_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=5),
        ),
    ]
