# Generated by Django 4.2.6 on 2023-12-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppFolder", "0007_orderitem_amount"),
    ]

    operations = [
        migrations.RenameField(model_name="order", old_name="item", new_name="items",),
    ]
